export const socia_media = [
    {
        id:1,
        name:"facebook",
        link:"https://web.facebook.com/"
    },
    {
        id:2,
        name:"instagram",
        link:"https://www.instagram.com/"
    },
    {
        id:3,
        name:"telegram",
        link:"https://web.telegram.org/"
    },
    {
        id:4,
        name:"twitter",
        link:"https://x.com/Accueil"
    },
    {
        id:5,
        name:"youtube",
        link:"https://www.youtube.com"
    }
]